Dinero y distintos fantasies
Edusus/project-ids-backend pull request #16
Opened 2022-12-29 22:56 UTC by HopeAero

Funcionalidad de dinero y fantasies completo con sus respuesta de documentacion

2022-12-30 12:02 UTC, Hector1567XD requested changes

2022-12-30 12:02 UTC, Hector1567XD commented on databases/db.js
> +Event.hasOne(money);
Entiendo que los eventos tienen distintos MONEY así mismo como los jugadores por que es una relacion Many to Many no?

```suggestion
Event.hasMany(money);
```

2022-12-30 12:02 UTC, Hector1567XD commented on databases/db.js
> +const money= moneyModel(sequelize,Sequelize);
Mayusculas para los modelos pls
```suggestion
const Money= moneyModel(sequelize,Sequelize);
```

2022-12-30 12:02 UTC, Hector1567XD commented on databases/db.js
> +    User, Sticker, Event, Promotion, ad, game, team, random, Op, inventory, money
Mayusculas para los modelos pls
```suggestion
    User, Sticker, Event, Promotion, ad, game, team, random, Op, inventory, Money
```

2022-12-30 12:02 UTC, Hector1567XD commented on models/moneyModel.js
> +    })
Y el id del jugador y el id del evento no se colocan aqui?

2022-12-30 12:02 UTC, Hector1567XD commented on routes/api/money.js
> +        res.json({error:'No existen eventos activos'});
Acomodar formato
```suggestion
    if (eventsPublics=='') {
        res.json({ 
             success: false,
             message :'No existen eventos activos'
        });
```

2022-12-30 12:02 UTC, Hector1567XD commented on routes/api/money.js
> +            return element;
Propuesta mas elegante
```suggestion
            });
            return {
                 ...element,
                 imAlreadyPlayingIn: !!moneyEvent,
            };
```

2022-12-30 12:02 UTC, Hector1567XD commented on routes/api/money.js
> +            const moneyEvent = await money.findOne({
```suggestion
            const moneyEvent = await Money.findOne({
```
pls

2022-12-30 12:02 UTC, Hector1567XD commented on routes/api/money.js
> +    }
Si lo haces como recomienda Rondon, y ademas usas Guard Clausures (lectura recomendada: https://artansoft.com/2017/01/guard-clauses-definicion-beneficios/), te sale mucho mejor quitar los "else" y poner "returns":

```suggestion
    if (!event) {
        return res.status(404).json({
            success: false,
            message: "Evento no encontrado"
        });
    }
  
    if(event.status == false){
        return res.status(403).json({
            success: false,
            message: "Este evento no esta activo"
        })
    }
    
    const user = await money.findOne({
        raw:true,
        attributes: {
            exclude: ['createdAt', 'updatedAt', 'id','userId','eventId']
        },
        where: {
            [Op.and]:[{
                eventId : req.params.eventId
            },
            {
                userId : req.user.id.id
            }]
        }
    });
 
    if (user) {
        return res.status(409).json({
            success: false,
            message: "Ya estas participando en ese evento"
        })
    }
  
    await money.create({
        eventId: req.params.eventId,
        userId: req.user.id.id,
        points: 0,
        money: 0
    });
  
    return res.status(200).json({
        success: true,
        message: "Felicidades te haz unido al fantasy "+event.eventName
    })
```

2022-12-30 12:03 UTC, Hector1567XD requested changes

2022-12-30 12:03 UTC, Hector1567XD commented on databases/db.js
> +const money= moneyModel(sequelize,Sequelize);
Otra cosa!, esto NO ES solo dinero, es Dinero y Puntaje, pero mas que eso, esto es el registro de que un jugador esta participando en el fantasy y adicionalmente tiene el dinero y puntaje, yo le pondria
```suggestion
const PlayerFantasy = playerFantasyModel(sequelize,Sequelize);
```
O...
```suggestion
const FantasyParticipation = fantasyParticipationModel(sequelize,Sequelize);
```
O...
```suggestion
const PlayerFantasyParticipation = playerFantasyParticipationModel(sequelize,Sequelize);
```
O no se, ustedes lo ven

2023-01-02 15:06 UTC, HopeAero commented on models/moneyModel.js
> +    })
nope, las relaciones que se declaran en el db hacen que el id del jugador y del evento las contenga la tabla money asi que los atributos que se declaren en el modelo seran los propios de esa tabla

2023-01-03 21:40 UTC, Noralgorithm approved these changes

2023-01-03 22:30 UTC, AureumBox approved these changes
Funciona bien

2023-01-03 22:30 UTC, AureumBox commented on routes/api/playerFantasyModel.js
> +        message: "Felicidades te haz unido al fantasy "+event.eventName
Nada de código, pero a 
```suggestion
        message: "Felicidades te has unido al fantasy "+event.eventName
```

2023-01-05 19:11 UTC, Hector1567XD commented on routes/api/playerFantasyModel.js
> +});
Bello este Endpoint @EduardoSucre <3 te felicito

2023-01-05 19:11 UTC, Hector1567XD requested changes

2023-01-05 19:11 UTC, Hector1567XD commented on routes/api/playerFantasyModel.js
> +router.get('/:eventId', async (req,res)=>{
Lo mismo que se hizo en `/:eventId/join-game` se puede y deberia hacer aqui usar Guard Clausures

2023-01-06 01:00 UTC, Edusus commented on routes/api/playerFantasyModel.js
> +});
Gracias amio

2023-01-06 01:04 UTC, Hector1567XD commented on routes/api/money.js
> +            return element;
Ok dejemos esto para despues

2023-01-06 01:50 UTC, Hector1567XD approved these changes
Espera el approve de @DaikoneKisu para poder pasarlo a prod

2023-01-06 17:34 UTC, DaikoneKisu commented on databases/db.js
> +//PlayerFantasy = playerFantasyModel
```suggestion
const PlayerFantasy= playerFantasyModel(sequelize,Sequelize);
```
Si no lus usan, mejor quitarlos que dejarlos comentados xd

2023-01-06 17:47 UTC, Edusus commented on databases/db.js
> +//PlayerFantasy = playerFantasyModel
Sii, se me olvidó quitar eso :(

2023-01-06 17:52 UTC, DaikoneKisu commented on models/playerFantasyModel.js
> +}
```suggestion
module.exports = (sequelize, type) => {
    return sequelize.define('playerFantasyModel', {
      id: {
        type: type.INTEGER,
        primaryKey: true,
        autoIncrement: true
      },
      points: {
        type: type.INTEGER,
        allowNull: false,
        defaultValue: 0,
      },
      money: {
        type: type.INTEGER,
        allowNull: false,
        defaultValue: 0,
      }
    })
}
```
Aunque coloquen el defaultValue como 0, todavía colocará este valor a NULL si lo permiten. Es mejor que directamente digan que no se le puede colocar NULL, o lo validen de alguna manera

2023-01-06 19:03 UTC, DaikoneKisu commented on routes/api/playerFantasyModel.js
> +});
Bellísimo

2023-01-06 19:21 UTC, DaikoneKisu approved these changes
Bello papa

2023-01-06 21:10 UTC, merged