Almacen de jugadores + plantilla de jugadores
Edusus/project-ids-backend pull request #17
Opened 2022-12-29 23:08 UTC by HopeAero

2022-12-30 12:09 UTC, Hector1567XD requested changes

2022-12-30 12:09 UTC, Hector1567XD commented on controllers/squad/finder.js
> +const { Warehouse, Sticker, team } = require('../../databases/db');
```suggestion
const { Warehouse, Sticker, Team } = require('../../databases/db');
```
Modelos en mayuscula pls

2022-12-30 12:09 UTC, Hector1567XD commented on controllers/squad/poster.js
> +        }
Si lo haces como recomienda Rondon, y ademas usas Guard Clausures (lectura recomendada: https://artansoft.com/2017/01/guard-clauses-definicion-beneficios/), te sale mucho mejor quitar los "else" y poner "returns":

```suggestion
        if (!warehouse) {
            return responses.errorDTOResponse(res, 404, 'No posees este Sticker')
        }
   
        const isInLineup = warehouse.isInLineup;
        if (isInLineup) {
            return responses.errorDTOResponse(res, 403, 'Este sticker ya esta en la alineacion')
        }
    
        const cont = await Warehouse.count({
            where: {
                [Op.and]: [{
                    userId: userId
                }, {
                    eventId: eventId
                }, {
                    isInLineup: true
                }]
            }
        })
       
        if (cont >= 11) {
            return responses.errorDTOResponse(res, 403, 'Ya tienes 11 stickers en la alineacion')
        }
       
        const updatedWarehouse = await Warehouse.update({
            isInLineup: true
        }, {
            where: {
                [Op.and]: [{
                    stickerId: playerId
                }, {
                    eventId: eventId
                },{
                    userId: userId
                }]
            }
        });
        return responses.successDTOResponse(res, 200, 'Sticker agregado a la alineacion') 
```

2022-12-30 12:15 UTC, Hector1567XD requested changes

2022-12-30 12:15 UTC, Hector1567XD commented on controllers/benches/finder.js
> +    let { page = 0, size = 10, playername: playerName = '.*', teamname = '%', position = ['arquero', 'defensa', 'delantero', 'medio campo'] } = req.query;
Con razon se andaban cayendo a coñazos ayer, los IDENTIFICADORES del backend son eso, IDENTIFICADORES no deben (necesariamente) corresponder al texto que se mostrara en el frontend, esto va en INGLES

Incluso lo dice la documentacion: https://www.notion.so/Gestion-de-cromos-961d780d45b942bdbb802d02de0687b4

```suggestion
    let { page = 0, size = 10, playername: playerName = '.*', teamname = '%', position = ['goalkeeper', 'defender', 'forward', 'midfield'] } = req.query;
```

2022-12-30 12:15 UTC, Hector1567XD commented on databases/db.js
> +Event.hasOne(Warehouse);
```suggestion
Event.hasMany(Warehouse);
```
Entiendo que, los eventos tienen VARIAS "warehouses" que realmente no son warehouses como tal si no la relacion entre un sticker ("jugador en este contexto"), un usuario y un evento

2022-12-30 12:15 UTC, Hector1567XD commented on databases/db.js
> +    User, Sticker, Event, ad, game, team, random, Op, inventory, Warehouse, Promotion
```suggestion
    User, Sticker, Event, Ad, Game, Team, Random, Op, Inventory, Warehouse, Promotion
```
Modelos en masyucula pls

2022-12-30 12:15 UTC, Hector1567XD commented on utils/responses/responses.js
> +const errorDTOResponse = (res, status, msg) => {
```suggestion
const errorDTOResponse = (res, status, message) => {
```
Esta mucho mejor asi

2022-12-30 12:15 UTC, Hector1567XD commented on utils/responses/responses.js
> +    message: msg
```suggestion
    message
```
Por que puedes hacer esto

2022-12-30 22:50 UTC, DaikoneKisu commented on controllers/squad/finder.js
> +const { Warehouse, Sticker, team } = require('../../databases/db');
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH

2022-12-30 22:51 UTC, DaikoneKisu commented on controllers/benches/finder.js
> +    let { page = 0, size = 10, playername: playerName = '.*', teamname = '%', position = ['arquero', 'defensa', 'delantero', 'medio campo'] } = req.query;
Chito

2022-12-30 22:52 UTC, DaikoneKisu commented on controllers/benches/finder.js
> +    let { page = 0, size = 10, playername: playerName = '.*', teamname = '%', position = ['arquero', 'defensa', 'delantero', 'medio campo'] } = req.query;
Aparte, el peo es que en la db de producción y staging, medio campo está guardado como MedioCampo, 'tonces igual esto doesn't works

2022-12-30 22:54 UTC, DaikoneKisu commented on databases/db.js
> +Event.hasOne(Warehouse);
Cñ, xd

2022-12-30 22:55 UTC, DaikoneKisu commented on databases/db.js
> +    User, Sticker, Event, ad, game, team, random, Op, inventory, Warehouse, Promotion
RANDOM NO ES UN MODELO

2022-12-30 22:56 UTC, DaikoneKisu commented on utils/responses/responses.js
> +const errorDTOResponse = (res, status, msg) => {
Cñ mano esa corrección ya está en main, cuando se mergee se elige aquella

2022-12-30 22:56 UTC, DaikoneKisu commented on utils/responses/responses.js
> +    message: msg
Cñ mano esa corrección ya está en main, cuando se mergee se elige aquella

2023-01-03 21:39 UTC, Noralgorithm approved these changes

2023-01-06 01:06 UTC, Hector1567XD commented on databases/db.js
> +    User, Sticker, Event, ad, game, team, random, Op, inventory, Warehouse, Promotion
Pero, si lo usan como una clase al igual que los modelos, deben cambiarlo a mayuscula, si es una variable simple ps ok, pero lo dudo xd

2023-01-06 01:07 UTC, Hector1567XD requested changes

2023-01-06 01:07 UTC, Hector1567XD commented on controllers/squad/poster.js
> +        }
Mira chamo hagan este fix que es importante

2023-01-06 01:07 UTC, Hector1567XD commented on controllers/benches/finder.js
> +    let { page = 0, size = 10, playername: playerName = '.*', teamname = '%', position = ['arquero', 'defensa', 'delantero', 'medio campo'] } = req.query;
Explicate

2023-01-06 01:09 UTC, Hector1567XD commented on databases/db.js
> +Event.hasOne(Warehouse);
Si o no xD? explicate chamo

Si la hiciste dale a "Resolver" si no, explicame por que para caernos a pingasos o para yo aprender xd

2023-01-06 01:21 UTC, Hector1567XD requested changes

2023-01-06 01:21 UTC, Hector1567XD commented on controllers/squad/poster.js
> +    }
Arregla la identacion y no olvides de colocar "return" despues de cada salida de respuesta
```suggestion
    const userId = req.user.id.id;
    const eventId = req.eventId;
    const { playerId } = req.body;

    let existe = await Warehouse.findOne({
        where: {
            eventId: eventId
        }
    });

    if (!existe) {
    return responses.errorDTOResponse(res, 403, 'Evento no encontrado');
    }

    const warehouse = await Warehouse.findOne({
        raw: true,
        where: {
            [Op.and]: [{
                stickerId: playerId
            }, {
                eventId: eventId
            },{
                userId: userId
            }]
        }
    });

    if (!warehouse) {
        return responses.errorDTOResponse(res, 404, 'No posees este Sticker')
    }

    const isInLineup = warehouse.isInLineup;
    if (isInLineup) {
        return responses.errorDTOResponse(res, 403, 'Este sticker ya esta en la alineacion')
    }
        
    const cont = await Warehouse.count({
        where: {
            [Op.and]: [{
                userId: userId
            }, {
                eventId: eventId
            }, {
                isInLineup: true
            }]
        }
    })

    if (cont >= 11) {
        return responses.errorDTOResponse(res, 403, 'Ya tienes 11 stickers en la alineacion')
    } 

    const updatedWarehouse = await Warehouse.update({
        isInLineup: true
    }, {
        where: {
            [Op.and]: [{
                stickerId: playerId
            }, {
                eventId: eventId
            },{
                userId: userId
            }]
        }
    });

    const goalkeeper = await Warehouse.count({
        where: {
            [Op.and]: [{
                userId: userId
            }, {
                eventId: eventId
            }, {
                isInLineup: true
            }]
        },
        include : {
            model: Sticker,
            where: {
                position: 'goalkeeper'
            }
        }
    });

    const defender = await Warehouse.count({
        where: {
            [Op.and]: [{
                userId: userId
            }, {
                eventId: eventId
            }, {
                isInLineup: true
            }]
        },
        include : {
            model: Sticker,
            where: {
                position: 'defender'
            }
        }
    });

    const midfielder = await Warehouse.count({
        where: {
            [Op.and]: [{
                userId: userId
            }, {
                eventId: eventId
            }, {
                isInLineup: true
            }]
        },
        include : {
            model: Sticker,
            where: {
                position: 'midfielder'
            }
        }
    });

    const forward = await Warehouse.count({
        where: {
            [Op.and]: [{
                userId: userId
            }, {
                eventId: eventId
            }, {
                isInLineup: true
            }]
        },
        include : {
            model: Sticker,
            where: {
                position: 'forward'
            }
        }
    });


    if (goalkeeper > 1) {
        await Warehouse.update({
            isInLineup: false
        }, {
            where: {
                [Op.and]: [{
                    stickerId: playerId
                }, {
                    eventId: eventId
                },{
                    userId: userId
                }]
            }
        });
        return responses.errorDTOResponse(res, 403, 'Ya tienes un arquero en la alineacion')
    } else if (defender > 4) {
        await Warehouse.update({
            isInLineup: false
        }, {
            where: {
                [Op.and]: [{
                    stickerId: playerId
                }, {
                    eventId: eventId
                },{
                    userId: userId
                }]
            }
        });
        return responses.errorDTOResponse(res, 403, 'Ya tienes 4 defensas en la alineacion')
    } else if (midfielder > 3) {
        await Warehouse.update({
            isInLineup: false
        }, {
            where: {
                [Op.and]: [{
                    stickerId: playerId
                }, {
                    eventId: eventId
                },{
                    userId: userId
                }]
            }
        });
        return responses.errorDTOResponse(res, 403, 'Ya tienes 3 medio campo en la alineacion')
    } else if (forward > 3) {
        await Warehouse.update({
            isInLineup: false
        }, {
            where: {
                [Op.and]: [{
                    stickerId: playerId
                }, {
                    eventId: eventId
                },{
                    userId: userId
                }]
            }
        });
        return responses.errorDTOResponse(res, 403, 'Ya tienes 3 delantero en la alineacion')
    } else {
        return responses.successDTOResponse(res, 200, 'Sticker agregado a la alineacion')  
    }

} catch (error) {
    console.error(error);
    return responses.errorDTOResponse(res, 403, error.message);
}
```

2023-01-06 01:37 UTC, Hector1567XD requested changes

2023-01-06 01:37 UTC, Hector1567XD commented on controllers/squad/poster.js
> +        }
No funciona esto?
```suggestion
        const goalkeeper = await Warehouse.count({
            where: {
                [Op.and]: [{
                    userId: userId
                }, {
                    eventId: eventId
                }, {
                    isInLineup: true
                }]
            },
            include: {
                model: Sticker,
                where: {
                    position: 'goalkeeper'
                }
            }
        });

        const defender = await Warehouse.count({
            where: {
                [Op.and]: [{
                    userId: userId
                }, {
                    eventId: eventId
                }, {
                    isInLineup: true
                }]
            },
            include: {
                model: Sticker,
                where: {
                    position: 'defender'
                }
            }
        });

        const midfielder = await Warehouse.count({
            where: {
                [Op.and]: [{
                    userId: userId
                }, {
                    eventId: eventId
                }, {
                    isInLineup: true
                }]
            },
            include: {
                model: Sticker,
                where: {
                    position: 'midfielder'
                }
            }
        });

        const forward = await Warehouse.count({
            where: {
                [Op.and]: [{
                    userId: userId
                }, {
                    eventId: eventId
                }, {
                    isInLineup: true
                }]
            },
            include: {
                model: Sticker,
                where: {
                    position: 'forward'
                }
            }
        });


        if (goalkeeper >= 1) {
            return responses.errorDTOResponse(res, 403, 'Ya tienes un arquero en la alineacion')
        } else if (defender >= 4) {
            return responses.errorDTOResponse(res, 403, 'Ya tienes 4 defensas en la alineacion')
        } else if (midfielder >= 3) {
            return responses.errorDTOResponse(res, 403, 'Ya tienes 3 medio campo en la alineacion')
        } else if (forward >= 3) {
            return responses.errorDTOResponse(res, 403, 'Ya tienes 3 delantero en la alineacion')
        } else {
            const updatedWarehouse = await Warehouse.update({
                isInLineup: true
            }, {
                where: {
                    [Op.and]: [{
                        stickerId: playerId
                    }, {
                        eventId: eventId
                    }, {
                        userId: userId
                    }]
                }
            });
      
            return responses.successDTOResponse(res, 200, 'Sticker agregado a la alineacion')
        }
```

2023-01-06 01:43 UTC, Hector1567XD approved these changes

2023-01-06 01:43 UTC, Hector1567XD commented on controllers/squad/poster.js
> +        }
La dejare como opcional, crea una tarea y la arreglas despues

2023-01-06 01:44 UTC, merged