Improvement/get items by
Edusus/project-ids-backend pull request #18
Opened 2023-01-06 20:54 UTC by Edusus

Revisen los endpoints para buscar usuarios, eventos y cromos por su id

2023-01-07 05:24 UTC, Hector1567XD requested changes

2023-01-07 05:24 UTC, Hector1567XD commented on routes/api/events.js
> +    const event= await Event.findOne({where:{id: req.params.eventId}});
Seria util

```suggestion
    if (!isNaN(req.params.eventId)) {
            return res.status(400).json({
               success: false,
               error:'El ID debe ser un numero'
             });
    }

    const event= await Event.findOne({where:{id: req.params.eventId}});
```

2023-01-07 05:24 UTC, Hector1567XD commented on routes/api/stickers.js
> +  const sticker= await Sticker.findOne({where:{id: req.params.stickerId}});
```suggestion
    if (!isNaN(req.params.stickerId)) {
            return res.status(400).json({
               success: false,
               error:'El ID debe ser un numero'
             });
    }

  const sticker= await Sticker.findOne({where:{id: req.params.stickerId}});
```

2023-01-07 05:24 UTC, Hector1567XD commented on routes/api/users.js
> +    const user1= await User.findOne({where:{id: req.params.userId}});
```suggestion
    if (!isNaN(req.params.userId)) {
            return res.status(400).json({
               success: false,
               error:'El ID debe ser un numero'
             });
    }
    
    const user1= await User.findOne({where:{id: req.params.userId}});
```

2023-01-07 05:24 UTC, Hector1567XD commented on routes/api/users.js
> +        });
```suggestion
        return res.status(404).json({
          success: false,
          error:'No existe usuario con este id'
        });
```

2023-01-07 05:24 UTC, Hector1567XD commented on routes/api/stickers.js
> +      });
```suggestion
      return res.status(404).json({
        success: false,
        error:'No existe cromo con este id'
      });
```

2023-01-07 05:24 UTC, Hector1567XD commented on routes/api/events.js
> +        });
```suggestion
        return res.status(404).json({
          success: false,
          error:'No existe ningun evento con este id'
        });
```

2023-01-07 22:54 UTC, Hector1567XD requested changes
Solo agrega los DTO´s y te doy approve :)

2023-01-08 01:22 UTC, luizzzito approved these changes
Los endpoints funcionan de forma correcta en el Postman, y tienen los mensajes de error correctos.

2023-01-08 03:00 UTC, Hector1567XD approved these changes
Bellisimo
![thumbs-up-approve](https://user-images.githubusercontent.com/22270579/211178528-ce88e307-a469-4450-89b1-d7f34b3b85cd.gif)

2023-01-08 03:19 UTC, DaikoneKisu commented on routes/api/events.js
> +    if (isNaN(req.params.eventId)) {
```suggestion
    if (Number.isNaN(req.params.eventId)) {
```
Mejor usa Number.isNaN(), no isNaN()

2023-01-08 03:21 UTC, DaikoneKisu commented on routes/api/events.js
> +    return responses.singleDTOResponse(res,200,"Recuperación exitosa",event);
```suggestion
    return responses.singleDTOResponse(res,200,"Evento recuperado con exito",event);
```
Mejor, más contextual

2023-01-08 03:22 UTC, DaikoneKisu commented on routes/api/stickers.js
> +  if (isNaN(req.params.stickerId)){
```suggestion
  if (Number.isNaN(req.params.stickerId)){
```
Lo mismo que en events

2023-01-08 03:22 UTC, DaikoneKisu commented on routes/api/stickers.js
> +  return responses.singleDTOResponse(res,200,"Recuperación exitosa",sticker);
```suggestion
  return responses.singleDTOResponse(res,200,"Sticker recuperado con exito",sticker);
```

2023-01-08 03:23 UTC, DaikoneKisu commented on routes/api/users.js
> +    if (isNaN(req.params.userId)) {
```suggestion
    if (Number.isNaN(req.params.userId)) {
```
Lo mismo que en stickers y eventos

2023-01-08 03:24 UTC, DaikoneKisu commented on routes/api/users.js
> +    return responses.singleDTOResponse(res,200,"Recuperación exitosa",user1);
```suggestion
    return responses.singleDTOResponse(res,200,"Usuario recuperado con exito",user1);

```

2023-01-08 03:36 UTC, DaikoneKisu commented on routes/api/users.js
> +  });
```suggestion
    const user = await User.findOne({
        where:{id: req.params.userId}
    });
     if(!user){
        return responses.errorDTOResponse(res, 404, "No existe usuario con este id");
    }
    return responses.singleDTOResponse(res,200,"Recuperación exitosa",user);
  });
```
Chequeen si eso furula así, no me parece que se llame user1 xd

2023-01-10 01:27 UTC, Hector1567XD commented
Already in `improvement/tengen-toppa-gurren-branch`

2023-01-10 01:27 UTC, Hector1567XD commented
Already in `improvement/tengen-toppa-gurren-branch`

2023-01-10 01:28 UTC, Hector1567XD commented
Already in `improvement/tengen-toppa-gurren-branch`

2023-01-10 01:29 UTC, Hector1567XD commented
Already in `improvement/tengen-toppa-gurren-branch`

2023-01-10 02:15 UTC, closed without merging