funcionalidad completa de mercado sin los filtros
Edusus/project-ids-backend pull request #19
Opened 2023-01-07 05:32 UTC by HopeAero

2023-01-07 20:47 UTC, Hector1567XD commented on routes/api/market2.js
> +  bid.value += 10;
```suggestion
  bid.value += 10;
```
¿Como asi?, por que siempre sube 10?

2023-01-07 20:48 UTC, Hector1567XD commented on routes/api/market2.js
> +const { Router } = require('express');
Sugiero cambiar el nombre a "market-mock" para evitar confusiones, yo pense que estos eran los endpoints y quede wtf

2023-01-07 20:51 UTC, Hector1567XD commented on routes/api/market2.js
> +    name: 'Senko-San uwu'
![senko-love](https://user-images.githubusercontent.com/22270579/211169839-ede4e26f-4689-4869-9a55-9b3ecccdde76.gif)

2023-01-07 21:22 UTC, Hector1567XD requested changes

2023-01-07 21:22 UTC, Hector1567XD commented on routes/api/market.js
> +        });
Usar DTO

2023-01-07 21:22 UTC, Hector1567XD commented on routes/api/market.js
> +    const winner = items.find(item => item.value === max);
Encalsulalo en una funcion aparte


```
function async getWinnerBid(marketId) {
    const marketBid = await Bid.findAll({
        raw:true,
        where:{ marketId }
    });
    const user = JSON.parse(JSON.stringify(marketBid));
    const items = [];
    for (let i = 0; i < user.length; i++) {
        items.push(user[i]);
    }
    const max = Math.max.apply(Math, items.map(function(o) { return o.value; }))
    const winner = items.find(item => item.value === max);
    return winner;
}
```

```suggestion
    const marketBid = await getWinnerBid(req.params.marketId);
```

Lejos de eso... mrc el obtener TODAS las pujas de unas ubasta me parece un poquito poco optimo para esto, creo que deberia haber una forma de ordenarlas descendentemente o algo asi y obtenerla de una, pero bueno..... igual tampoco es tan terrible supongo no existiara una sola subasta con 3510501501 pujas, solo digo que podria mejorar

2023-01-07 21:22 UTC, Hector1567XD commented on routes/api/market.js
> +    });
Noentiendo.... ¿por que haces esto?, la puja mas alta no deberia ser la misma que tu ultima puja? y.... para que quisieras siquiera saber de multiples pujas? tu ultima puja no anula automaticamente tu puja mas alta?

2023-01-07 21:22 UTC, Hector1567XD commented on routes/api/market.js
> +    }
Esto no va paginado??, y por que ese error? si no hay subastas envien un arreglo vacio y ya, ademas nisiquiera sigue el formato

Tambien, seria bueno un try y un catch

2023-01-07 21:22 UTC, Hector1567XD commented on routes/api/inventory.js
> +                                 [Op.and]: [{stickerId: stickerId},{eventId : eventId},{userId: req.user.id.id}]
Increible
```suggestion
                                 [Op.and]: [{ stickerId },{ eventId },{ userId: req.user.id.id }]
```

2023-01-07 21:22 UTC, Hector1567XD commented on routes/api.js
> +router.use('/ads', adsRouter); //Vieja implementacion de ads
```suggestion
```
Esta cosa hay que borrarla, pero bueno, no en este PR

2023-01-07 21:22 UTC, Hector1567XD commented on models/market.js
> +                msg: "Error: finishDate must not be empty"
Si son mensajes que se envian al frontend, ps en español xd
```suggestion
                msg: "finishDate debe ser una fecha valida"
            },
            notEmpty: {
                args: true,
                msg: "finishDate debe ser una fecha valida"
```

2023-01-07 21:22 UTC, Hector1567XD commented on models/bids.js
> +                    msg: "Error: value must not be empty"
Lo mismo español...

2023-01-07 21:22 UTC, Hector1567XD commented on controllers/market/updater.js
> +    if (market.immediatePurchaseValue == value && isDirectPurchase) {
Creo que esto es inncesario, cuando es compra directa podemos omitir el value pt1
```suggestion
    if (isDirectPurchase) {
```

2023-01-07 21:22 UTC, Hector1567XD commented on controllers/market/updater.js
> +            money: player.money - value
Creo que esto es inncesario, cuando es compra directa podemos omitir el value pt2
```suggestion
            money: player.money - market.immediatePurchaseValue
```

2023-01-07 21:22 UTC, Hector1567XD commented on controllers/market/updater.js
> +    }
Creo que esto es inncesario, cuando es compra directa podemos omitir el value pt3
```suggestion
    if (!isDirectPurchase && bid.value > value) {
        return responses.errorDTOResponse(res, 400, 'El valor de la oferta debe ser mayor al valor inicial');
    }
```
Esto para bypassear u omitir esta validacion si es que es una compra directa

2023-01-07 21:22 UTC, Hector1567XD commented on controllers/market/updater.js
> +    if (player.money < value) {
Creo que esto es inncesario, cuando es compra directa podemos omitir el value pt4

Aaaah..... con razon lo hiciste asi, bueno:
```suggestion
    if ((!isDirectPurchase && player.money < value) || (isDirectPurchase && player.money < market.immediatePurchaseValue)) {
```
Con derivaciones booleanas esto se puede optimizar, pero bueno, te lo dejo a ti o a @DaikoneKisu esa optimizacion

2023-01-07 21:22 UTC, Hector1567XD commented on controllers/market/updater.js
> +    }
Creo que esto es inncesario, cuando es compra directa podemos omitir el value pt4
```suggestion
    if ((value == null && !isDirectPurchase) || marketId == null) {
        return responses.errorDTOResponse(res, 400, 'Debe proporcionar un valor y un marketId');
    }
```

2023-01-07 21:22 UTC, Hector1567XD commented on controllers/market/updater.js
> +const bidUpdate = async (req, res) => {
Violas mucho el DRY, opcionalmente te pido que busques dividir esto en varias funciones pequeñas para mejorar la lectura del codigo y no violar el DRY 😢

2023-01-07 21:22 UTC, Hector1567XD commented on controllers/market/poster.js
> +const posterBid = async (req, res) => {
Las mismas correciones que hice en el updater

2023-01-07 21:22 UTC, Hector1567XD commented on controllers/market/updater.js
> +    if (market.immediatePurchaseValue == value && isDirectPurchase) {
una cosa, ¿POR QUE puedes editar una oferta que es compra directa si cuando haces una **COMPRA DIRECTA** lo compras de una vez?, no debería cerrar la subasta completa al hacer una compra directa?

2023-01-07 21:22 UTC, Hector1567XD commented on controllers/market/poster.js
> +            return responses.singleDTOResponse(res, 200, 'Compra realizada con exito', market);
Si la subasta termina, por que no se devuelve el dinero al resto de jugadores que apostaron en ella que no ganaron?

2023-01-07 21:22 UTC, Hector1567XD commented on controllers/market/poster.js
> +const poster = async (req, res) => {
Lo revisare leugo de que hagas el resto de correcoines

2023-01-07 21:22 UTC, Hector1567XD commented on controllers/market/poster.js
> +            schedule.cancelJob(job);
TODA esta funcion, la puedes centralizar en una funcion tipo
```
 await finalizarSubasta(...);
```
De modo que puedas REUTILIZARLA al momento de crear (o editar?) una oferta de COMPRA DIRECTA y asi devuelves la plata al resto de jugadores y asi

2023-01-07 21:22 UTC, Hector1567XD commented on controllers/market/poster.js
> +            money: player.money - value
Cosas raras, MUY raras, pero...

Si yo hice una primera subasta de "500$" y me restaron los "500$" y ahora quiero editarla para que sea de "750$", deberia restarme "250$" pero entonces me va a restar "750$" habiendome restado EN TOTAL "1250$" no?

2023-01-07 21:22 UTC, Hector1567XD commented on controllers/market/poster.js
> +        return responses.errorDTOResponse(res, 403, 'No posees mas stickers de este tipo')
```suggestion
        return responses.errorDTOResponse(res, 403, 'Este jugador ya esta en la alineacion')
    }

    if (initialValue == null || directPurchase == null || playerId == null) {
      return responses.errorDTOResponse(res, 400, 'Debe proporcionar un valor inicial, un valor de compra directa y un playerId');
    }

    if (warehouse.quantity == 0) {
        return responses.errorDTOResponse(res, 403, 'No posees a ese jugador')
```

2023-01-07 21:22 UTC, Hector1567XD commented on controllers/market/poster.js
> +    if (isInLineup) {
Aqui hay un problema, que pasa si yo tengo 2 messis, uno esta en mi alineacion y el otro lo quiero subastar, entonces no me va a dejar subastar el que no lo tengo en mi alineacion por que tengo uno que si xD

@DaikoneKisu las desventajas de fusionar las tablas v:

Igual... CREO se puede arreglar:
```suggestion
    if (isInLineup || warehouse.quantity >= 2) {
```

2023-01-07 21:22 UTC, Hector1567XD commented on controllers/market/poster.js
> +    if (warehouse.quantity == 0) {
```suggestion
    if (warehouse.quantity <= 0) {
```

2023-01-07 22:15 UTC, HopeAero commented on routes/api/market2.js
> +const { Router } = require('express');
va

2023-01-07 22:15 UTC, HopeAero commented on routes/api/market.js
> +        });
fallo mio ahi xD

2023-01-07 22:16 UTC, HopeAero commented on routes/api/market.js
> +    const winner = items.find(item => item.value === max);
A ver creo que se podria mejorar pero podriamos dejarlo mientras asi y corregirlo en otro PR mientras middle trabaja con esto funcional eso si dejame ver si eso lo puedo encapsular

2023-01-07 22:19 UTC, HopeAero commented on controllers/market/poster.js
> +            money: player.money - value
Esa funa si me gusto pq me volvi un culo con las operaciones matematicas xD

2023-01-07 22:20 UTC, HopeAero commented on controllers/market/poster.js
> +    if (isInLineup) {
0.0

2023-01-07 22:35 UTC, HopeAero commented on routes/api/market.js
> +    }
mi loco eso ya esta paginado no vez el options gei eso si no manda el formato de respuesta correcto

2023-01-07 22:35 UTC, HopeAero commented on routes/api/market.js
> +    }
le falta el paginate: { mamadores de machetes }

2023-01-08 01:34 UTC, Hector1567XD requested changes

2023-01-08 01:34 UTC, Hector1567XD commented on controllers/market/poster.js
> +                console.log('No hay ofertas');
```suggestion
```

2023-01-08 01:34 UTC, Hector1567XD commented on routes/api/market.js
> +    }
Bueno mmgvo, pero manda el formato de paginacion correcto

2023-01-08 01:34 UTC, Hector1567XD commented on routes/api/market.js
> +    }
Si no hay ofertas, envien un arreglo vacio no envien "No hay ofertas".
```suggestion
    const marketActives= await Market.findAll(options);
    res.status(200).json({
        success: true,
        items : marketActives
    });
```

2023-01-08 01:53 UTC, Hector1567XD requested changes

2023-01-08 01:53 UTC, Hector1567XD commented on routes/api/market.js
> +router.post('/add', poster);
Cambios en la doc propuestos por mi y por @Noralgorithm 
```suggestion
router.post('/', poster);
```

2023-01-08 02:00 UTC, Hector1567XD requested changes

2023-01-08 02:00 UTC, Hector1567XD commented on routes/api/market.js
> +        res.status(200).json({
```suggestion
    }else{
        const items = marketActivies.map((marketActive) => {
           return { ...marketActive, isMine: (marketActive.userId === EL_USER_ID) };
        });
        res.status(200).json({
```

2023-01-08 02:00 UTC, Hector1567XD commented on routes/api/market.js
> +        res.status(200).json({
Lo hablado con Jose Andres, y dependiendo de lo que diga Paula

2023-01-09 04:34 UTC, Hector1567XD commented on routes/api/market.js
> +        res.status(200).json({
Ya se descarto.

2023-01-09 04:34 UTC, Hector1567XD commented on routes/api/market.js
> +router.post('/add', poster);
Finalmente sera
```suggestion
router.post('/auction', poster);
```

2023-01-10 04:24 UTC, closed without merging