Ads staging
Edusus/project-ids-backend pull request #2
Opened 2022-11-09 07:13 UTC by DaikoneKisu

CRUD de anuncios, con paginación y filtrado por parámetros query.

2022-11-16 05:57 UTC, Hector1567XD requested changes

2022-11-16 05:57 UTC, Hector1567XD commented on .env
> +PORT=
.gitignore papa

2022-11-18 14:45 UTC, DaikoneKisu commented on .env
> +PORT=
Oc

2022-11-21 12:49 UTC, Hector1567XD requested changes

2022-11-21 12:49 UTC, Hector1567XD commented on .gitignore
> +ads
watafa, por que "ads" es gitignore ?

2022-11-21 12:49 UTC, Hector1567XD commented on routes/api.js
> +router.use('/ads', adsRouter);
Lamento que te enteraras tan tarde u-u, pero desde los embajadores de BDD2 cambiamos el nombre `ads` por que provocaba problemas con ad-blocks, de momento el unico nombre que quedo fue `pop-ups` creo, cualquier cosa me corrijen, pero yo le pondria ese

FYI @Paulaforero @HopeAero @Edusus @Nannajpg @Noralgorithm 
```suggestion
router.use('/pop-ups', adsRouter);
```

2022-11-21 12:49 UTC, Hector1567XD commented on routes/api/ads.js
> +module.exports = adsRouter;
Me habias mostrado algo muy lindo con controladores y tal, ¿donde quedo eso?

2022-11-21 12:49 UTC, Hector1567XD commented on routes/api/ads.js
> +adsRouter.get('/search', async (req, res) => {
Creo que estas son las que manejamos, para la lista neta "/all" (que no se si haya falta lista neta en ads 🤔 ) y.... para la paginacion normal el nombre del recurso y listo

```suggestion
adsRouter.get('/all', async (req, res) => {
  const ads = await ad.findAll();
  httpGetResponse(res, ads, 'ads');
});

adsRouter.get('/', async (req, res) => {
```

2022-11-21 12:49 UTC, Hector1567XD commented on routes/api/ads.js
> +const allowedFields = ['announcer', 'adType', 'redirecTo', 'img'];
Desde embajadores de BDD2, agregamos el nuevo campo "description", falta tambien el campo "alias" te recomiendo revisar el modelo de ADS en el notion de BDD2

FYI @Paulaforero @HopeAero @Edusus @Nannajpg

```suggestion
const allowedFields = ['announcer', 'adType', 'redirecTo', 'img', 'description', 'alias'];
```

2022-11-21 12:49 UTC, Hector1567XD commented on routes/api/ads.js
> +const allowedFields = ['announcer', 'adType', 'redirecTo', 'img'];
A todas estas, para que es la propiedad "announcer" 🤔 ?

2022-11-21 12:49 UTC, Hector1567XD commented on routes/api/ads.js
> +}
Me gusta tu iniciativa por hacer cumpir el DRY UwU pero...

Veo esta abstraccion/generalizacion un poco extraña 🤔 , siendo el unico sitio donde es realmente requerida el cuando buscas un AD individual, ya que el resto de sitios o envias un objeto con datos de paginacion que desde luego nunca sera nulo, o envias un arreglo de ads

En el caso de enviar un arreglo vacio de ADS nunca se cumplira la condicion negativa por que los arreglos no son un objeto de tipo `falsy` o `nullish` (hasta donde yo sepa), pero INCLUSIVE aunque se cumpliese esta condicion, yo no espero que el endpoint retorne error 404, yo espero que el endpoint retorne un arreglo vacio xD y en el frontend poner "No hay elementos creados"

Reitero, solo lo veo util para el caso de un AD en especifico, alli si hay que enviar al front un 404 si no existe, es el unico, recomiendo eliminarla y poner esto directamente en esa ruta nada mas

2022-11-25 23:49 UTC, HopeAero approved these changes

2022-12-07 22:15 UTC, Noralgorithm approved these changes
LGTM

2022-12-11 12:10 UTC, DaikoneKisu commented on .gitignore
> +ads
Ni yo recuerdo, creo que era q tenía esa wea toa recursiva curseada xd

2022-12-11 12:11 UTC, DaikoneKisu commented on routes/api/ads.js
> +module.exports = adsRouter;
Ya pagué la deuda, y te traigo más papa

2022-12-11 12:12 UTC, DaikoneKisu commented on routes/api/ads.js
> +const allowedFields = ['announcer', 'adType', 'redirecTo', 'img'];
Announcer era === alias xd

2022-12-11 12:12 UTC, DaikoneKisu commented on routes/api/ads.js
> +const allowedFields = ['announcer', 'adType', 'redirecTo', 'img'];
Era, ya lo cambié

2022-12-11 12:13 UTC, DaikoneKisu commented on routes/api/ads.js
> +}
a

2022-12-15 19:23 UTC, Hector1567XD commented on utils/responses/responses.js
> +}
```suggestion
const multipleDTOsResponse = (res, status, message, items) => {
  return res.status(status).json({
    success: true,
    message,
    items
  });
}
```

2022-12-15 19:23 UTC, Hector1567XD commented on utils/responses/responses.js
> +}
```suggestion
const successDTOResponse = (res, status, message) => {
  return res.status(status).json({
    success: true,
    message
  });
}
```

2022-12-15 19:23 UTC, Hector1567XD commented on utils/responses/responses.js
> +}
```suggestion
const errorDTOResponse = (res, status, message) => {
  return res.status(status).json({
    success: false,
    message
  });
}
```

2022-12-15 19:24 UTC, Hector1567XD commented on utils/responses/responses.js
> +}
```suggestion
const paginatedDTOsResponse = (res, status, message, items, total, page, perPage) => {
  return res.status(status).json({
    success: true,
    message,
    paginate: {
      total,
      page,
      pages: Math.ceil(total/perPage),
      perPage
    },
    items
  });
}
```

2022-12-15 19:24 UTC, Hector1567XD commented on utils/responses/responses.js
> +}
```suggestion
const singleDTOResponse = (res, status, message, item) => {
  return res.status(status).json({
    success: true,
    message,
    item
  });
}
```

2022-12-15 19:25 UTC, Hector1567XD commented on utils/helpers/get-image-url.js
> +  const img_relative_dir = '/' + imgController.img_relative_dir.replaceAll('\\', '/') + '/';
o.0???

2022-12-15 19:27 UTC, Hector1567XD requested changes

2022-12-15 19:27 UTC, Hector1567XD commented on controllers/promotions/deleter.js
> +    const { img: fileurl } = Promotion;
```suggestion
    const promotion = await Promotion.findByPk(promotionId);
    if (typeof promotion === 'undefined' || promotion === null)
      return responses.errorDTOResponse(res, 404, 'Promocion no encontrada');

    const { img: fileurl } = promotion;
```
Porfavor... enserio porfavor ;u;

2022-12-16 00:48 UTC, DaikoneKisu commented on controllers/promotions/deleter.js
> +    const { img: fileurl } = Promotion;
Ño e tu madre

2022-12-16 00:48 UTC, DaikoneKisu commented on controllers/promotions/deleter.js
> +    const { img: fileurl } = Promotion;
Si explota es tu culpa, njd, corregir otra vaina más

2022-12-16 00:48 UTC, DaikoneKisu commented on controllers/promotions/deleter.js
> +    const { img: fileurl } = Promotion;
Ya la comiteo y resuelvo luego si explota

2022-12-16 00:52 UTC, DaikoneKisu commented on utils/helpers/get-image-url.js
> +  const img_relative_dir = '/' + imgController.img_relative_dir.replaceAll('\\', '/') + '/';
Con esto guardo el url de la imagen en la db, o sea, lo q necesitarán en middleware para recuperar la imagen, pq ajá, a ellos no les interesa el path, sino la url

2022-12-20 17:47 UTC, HopeAero approved these changes
ta fino mi yocuuu

2022-12-22 14:17 UTC, merged