Hotfix ads
Edusus/project-ids-backend pull request #20
Opened 2023-01-07 16:50 UTC by HopeAero

funcionalidad de ver anuncio y ver anuncio detallado en el cambio de endpoint de ads a promotion

2023-01-07 20:45 UTC, Hector1567XD requested changes
Estoy muy confundido, ¿esto no lo habia hecho daikone? @DaikoneKisu, ademas, creo hay diferencias con la documentacion y... tambien donde esta el endpoint del 302?

Tambien, si estoy empieza a estar en funcionamiento, super necesario que BORREMOS ADS los antiguos, por que si no habra confusion

2023-01-07 20:45 UTC, Hector1567XD commented on routes/api/promotions.js
> +      console.error(error);
```suggestion
```

2023-01-07 20:45 UTC, Hector1567XD commented on routes/api/promotions.js
> +      });
Usar DTO de Daikone

2023-01-07 20:45 UTC, Hector1567XD commented on routes/api/promotions.js
> +    let valorNuevo = valorActual + cont;
```suggestion
    const INCREMENTADOR = 1;
    const singleAd = await Promotion.findOne({ order: random});
    let actualRequestedQuantity = singleAd.dataValues.requestedQuantities;
    let requestedQuantity = actualRequestedQuantity + INCREMENTADOR;
```

2023-01-07 20:45 UTC, Hector1567XD commented on routes/api/promotions.js
> +    return res.status(200).json({ success: true, data: singleAd });
1. Hace falta el await
2. Agreguemos un try y un catch por si acaso
3. Usa DTOs de Daikone
```suggestion
    try {
        await singleAd.update({ requestedQuantities: requestedQuantity });
        return res.status(200).json({ success: true, data: singleAd }); // USAR DTOs
    } catch {
        return res.status(500).json({ success: false, message: "Error desconocido al actualizar la cantidad de renderizaciones del anuncio" })
    }
```

Otra cosa...
4. ¿No deberia ser "item"?, ¿como esta en la doc?
```suggestion
    try {
        await singleAd.update({ requestedQuantities: requestedQuantity });
        return res.status(200).json({ success: true, item: singleAd }); // USAR DTOs
    } catch {
        return res.status(500).json({ success: false, message: "Error desconocido al actualizar la cantidad de renderizaciones del anuncio" })
    }
```

2023-01-07 20:45 UTC, Hector1567XD commented on routes/api/promotions.js
> +       res.status(200).json({ success: true });
Falta try y catch por si las moscas
```suggestion
       await promotion.update({ clickedQuantities: valorNuevo });
       res.status(200).json({ success: true });
```
Otra cosa, esto no habia cambiado? para ser una redireccion 302?? 🤔

2023-01-08 04:05 UTC, DaikoneKisu commented
Borren esto xd

2023-01-09 08:18 UTC, DaikoneKisu commented on routes/api/promotions.js
> +    let valorNuevo = valorActual + cont;
Esto es una cagada

2023-01-09 08:20 UTC, DaikoneKisu commented on routes/api/promotions.js
> +    return res.status(200).json({ success: true, data: singleAd });
?

2023-01-09 08:20 UTC, DaikoneKisu commented on routes/api/promotions.js
> +       res.status(200).json({ success: true });
xd

2023-01-10 02:52 UTC, Hector1567XD commented
Already in `improvement/tengen-toppa-gurren-branch`

2023-01-10 02:52 UTC, closed without merging