Hotfix/endpoints responses
Edusus/project-ids-backend pull request #22
Opened 2023-01-08 00:43 UTC by Edusus

Endpoint para borrar cromos solo si no estan en album ni almacen

2023-01-08 02:57 UTC, Hector1567XD requested changes

2023-01-08 02:57 UTC, Hector1567XD commented on routes/api/stickers.js
> +      console.error(error);
```suggestion
```

2023-01-08 02:57 UTC, Hector1567XD commented on routes/api/stickers.js
>      });
Arreglar identacion y.... si puedes usar el DTO, genial!, tambien cambiar el texto a "Cromo borrado con exito!"
```suggestion
        });
        return res.status(200).json({ 
          success:true, 
          message:"Cromo borrado con exito!"
        });
```

2023-01-08 02:57 UTC, Hector1567XD commented on routes/api/stickers.js
> +    }
Muy buen nombre para las variables!!

2023-01-08 04:29 UTC, DaikoneKisu commented on routes/api/stickers.js
> +    }
No estoy de acuerdo, malísimos, misleading

2023-01-08 04:29 UTC, DaikoneKisu commented on routes/api/stickers.js
> +    }
Nah broma, arrechito papa

2023-01-08 04:29 UTC, Edusus commented on routes/api/stickers.js
> +    }
Dios mío, gracias

2023-01-08 04:32 UTC, DaikoneKisu commented on routes/api/stickers.js
>        message:"item deleted"
```suggestion
    return responses.successDTOResponse(res, 200, "Sticker eliminado con exito");
```
OJO PELAO, NO USA RESPONSES
Revisen la sugerencia igual, que furule xd

2023-01-08 04:32 UTC, DaikoneKisu commented on routes/api/stickers.js
> +      console.error(error);
?

2023-01-08 04:51 UTC, Edusus commented on routes/api/stickers.js
> +      console.error(error);
Que lo elimine?

2023-01-10 02:46 UTC, Hector1567XD commented
Already in `improvement/tengen-toppa-gurren-branch`

2023-01-10 02:46 UTC, closed without merging