Chromes
Edusus/project-ids-backend pull request #3
Opened 2022-11-09 14:38 UTC by DaikoneKisu

Salcedinho desde la cuenta del daikone subiendo esta mrd

2022-11-09 15:31 UTC, Hector1567XD requested changes

2022-11-09 15:31 UTC, Hector1567XD commented on .env
> +AUTH_SECRET = 8#FS09GFD
Hacer gitignore

2022-11-09 15:34 UTC, Hector1567XD requested changes

2022-11-09 15:34 UTC, Hector1567XD commented on databases/db.js
> +});
```suggestion
const sequelize = new Sequelize('offside','root','',{
    host:'127.0.0.1',
    dialect:'mysql'
});
```
Variables de entorno

2022-11-09 15:34 UTC, Hector1567XD commented on routes/api/auth.js
> +});
Funcion demaciado gigantesca, crear un controlador para encapsular su logica y funciones auxiliares, porfavor hablen con Gabriel para que les comente acerca de separar por funciones como recomienda el tio bob

Igual, esto es opcional, de todas formas este backend morira tarde o temprano

2022-11-09 15:34 UTC, Hector1567XD commented on controller/authcontroller.js
> +                  const linkVerification = `http://localhost:3000/new-password/${token}`
```suggestion
                  const linkVerification = `${DOMAIN}/new-password/${token}`
```
DOMAIN debe ser una variable de entorno

2022-11-10 01:41 UTC, AlejandroJRosas requested changes
Con respecto a la API del CRUD de Cromos:
1. Cambios en los Atributos necesarios en los endpoints de playerName a id (primary key)
2. Implementación de función en la API para devolver MAX(ID) de BD para usar en el front para el Hook de State

2022-11-10 02:44 UTC, AureumBox commented on routes/api/chromes.js
> +    res.status(200).json({message: 'Lista de usuarios', users });
```suggestion
    res.status(200).json({message: 'Lista de usuarios', chromes });
```
Devuelve los cromos, no los usuarios. Cambio sugerido para mejorar la claridad

2022-11-10 02:46 UTC, AureumBox commented on package.json
> +  "dependencies": {
Agregar "cors" a dependencias

2022-11-10 02:49 UTC, AureumBox commented on package.json
> +  "dependencies": {
Agregar "cors" a dependencias

2022-11-10 02:57 UTC, AureumBox requested changes
2 cambios sugeridos + 1 sugerencia general: cambiar todos los 'chromes' por 'stickers' para usar un mismo término entre backend y frontend.

2022-11-10 02:57 UTC, AureumBox commented on package.json
> +  "dependencies": {
Agregar "cors" a dependencias

2022-11-10 02:57 UTC, AureumBox commented on routes/api/chromes.js
> +    res.status(200).json({message: 'Lista de usuarios', users });
```suggestion
    res.status(200).json({message: 'Lista de cromos', chromes });
```
Devuelve los cromos, no los usuarios. Cambio sugerido para mejorar la claridad

2022-11-15 00:36 UTC, HopeAero approved these changes

2022-11-15 02:43 UTC, Noralgorithm approved these changes

2022-11-15 02:43 UTC, Noralgorithm commented on routes/api/chromes.js
> +    const users = await Chrome.findAll(options);
```suggestion
    const stickers = await Chrome.findAll(options);
```
cambiar nombre de la variable a stickers

2022-11-15 02:43 UTC, Noralgorithm commented on routes/api/chromes.js
> +    res.status(200).json({message: 'Lista de usuarios', users });
```suggestion
    res.status(200).json({message: 'Lista de cromos', stickers});
```

2022-11-15 22:08 UTC, HopeAero commented on routes/api/chromes.js
> +    const users = await Chrome.findAll(options);
listo papi

2022-11-15 22:08 UTC, HopeAero commented on routes/api/chromes.js
> +    res.status(200).json({message: 'Lista de usuarios', users });
listo tambien mi rey

2022-11-16 11:35 UTC, Hector1567XD requested changes
Señor salcediño, parele balls a Auri-god 👀 , vamos a cambiar `chromes` por `stickers`, lo decidimos en el grupo de Backend

2022-11-16 11:35 UTC, Hector1567XD commented on databases/db.js
> +const ChromeModel = require('./../models/chromes');
```suggestion
const StickerModel = require('./../models/stickers');
```

2022-11-16 11:35 UTC, Hector1567XD commented on databases/db.js
> +const Chrome = ChromeModel(sequelize,Sequelize);
```suggestion
const Sticker = StickerModel(sequelize,Sequelize);
```

2022-11-16 11:35 UTC, Hector1567XD commented on databases/db.js
> +    User, Chrome, Event
```suggestion
    User, Sticker, Event
```

2022-11-16 11:35 UTC, Hector1567XD commented on models/chromes.js
> +    return sequelize.define('chrome',{
```suggestion
    return sequelize.define('sticker',{
```

2022-11-16 11:35 UTC, Hector1567XD commented on routes/api.js
> +const apiChromesRouter = require('./api/chromes');
```suggestion
const apiStickersRouter = require('./api/stickers');

```

2022-11-16 11:35 UTC, Hector1567XD commented on routes/api.js
> +router.use('/chromes',apiChromesRouter);
```suggestion
router.use('/stickers',apiStickersRouter);

```

2022-11-16 11:35 UTC, Hector1567XD commented on routes/api/chromes.js
> +const { Chrome }= require('../../databases/db');
```suggestion
const { Sticker }= require('../../databases/db');
```

2022-11-16 11:35 UTC, Hector1567XD commented on routes/api/chromes.js
> +    const stickers = await Chrome.findAll(options);
```suggestion
    const stickers = await Sticker.findAll(options);
```

2022-11-16 11:35 UTC, Hector1567XD commented on routes/api/chromes.js
> +  const maxid = await Chrome.max("id");
```suggestion
  const maxid = await Sticker.max("id");
```

2022-11-16 11:35 UTC, Hector1567XD commented on routes/api/chromes.js
> +        where:{ id: req.params.playerId }
```suggestion
    const sticker = await Sticker.create(req.body);
    res.json(chrome);
});

//endpoint para editar cromos
router.put('/:playerId', async (req,res)=>{
    await Sticker.update(req.body,{
        where:{ id: req.params.playerId }
    });
    res.json({ success:'Se ha modificado'});
});

//endpoint para borrar cromos
router.delete('/:playerId', async (req,res)=>{
    await Sticker.destroy({
        where:{ id: req.params.playerId }
```

2022-11-16 11:36 UTC, Hector1567XD commented on routes/api/chromes.js
> +    const users = await Chrome.findAll(options);
@HopeAero la idea no seria solo aplicarlo puntualmente a 1 solo sitio xDDDD, si no, literal aplicarlo a todos los sitios donde se hace referencia a cromos (o en este caso a otra entidad de forma errada)

2022-11-17 00:45 UTC, AureumBox commented on config/auth.js
> +    rounds: process.env.ATUH_ROUNDS || 10,
```suggestion
    rounds: process.env.AUTH_ROUNDS || 10,
```

2022-11-17 01:33 UTC, AureumBox reviewed
Typo and delete unused endpoint

2022-11-17 01:33 UTC, AureumBox commented on routes/api/chromes.js
> +//endpoint para recuperar el mayor id
Esta realmente no se va a usar ya, porque usamos la misma respuesta del post

2022-11-17 01:33 UTC, AureumBox commented on config/auth.js
> +    rounds: process.env.ATUH_ROUNDS || 10,
```suggestion
    rounds: process.env.AUTH_ROUNDS || 10,
```

2022-11-17 04:13 UTC, AlejandroJRosas approved these changes
Machete

2022-11-18 00:21 UTC, AureumBox approved these changes

2022-11-18 01:42 UTC, Crismp02 approved these changes
Todo bello <3

2022-11-20 21:31 UTC, Hector1567XD approved these changes

2022-11-20 21:36 UTC, merged