subir imagenes al servidor
Edusus/project-ids-backend pull request #5
Opened 2022-11-21 04:47 UTC by HopeAero

2022-11-21 12:50 UTC, Hector1567XD commented
Bueno aja, y tu que, solicitame review

2022-11-23 03:21 UTC, AlejandroJRosas approved these changes

2022-11-24 08:26 UTC, Hector1567XD requested changes
Hagan la carpeta `/uploads/` .gitignore xd

2022-11-24 08:31 UTC, Hector1567XD requested changes

2022-11-24 08:31 UTC, Hector1567XD commented on controller/upload.js
> +      img: file,
```suggestion
      img: `${process.env.DOMAIN}/${file}`,,
    });
    res.status(201).json(newAd);
  } catch (error) {
    console.error(error);
    res.status(400).send(error.message);
  }
};

exports.uploadUpdatedFileAd = async (req, res) => {
  try {
    const file = req.file.path;
    const { announcer, adType, redirecTo } = req.body;
    await ad.update({
      announcer,
      adType,
      redirecTo,
      img: `${process.env.DOMAIN}/${file}`,,
```

O planean usar `OFFSITEIMGURL` ? o algo asi?

2022-11-24 08:31 UTC, Hector1567XD commented on controller/upload.js
> +
Las funciones 
- exports.uploadFileSticker
- exports.uploadFileAd
- exports.uploadUpdatedFileAd

No deberian estar aqui!, su lugar es en sus respectivos controladores por que contienen logica de negocio, lo unico centralizado deberia ser el "uploadFilter" que es compartido para todos y no tiene logica de negocio especifica

2022-11-26 01:51 UTC, AureumBox approved these changes

2022-12-06 21:30 UTC, Hector1567XD commented on controller/uploadAd.js
> +
Esto debería estar en su controllador, es decir en 
`controller/ads.js`

Pero me gusta que esté separado, si no, el controlador llegaría a tener 40000 lineas de codigo, pero en ese caso, esta debería ser una función que se exporte de una ruta como `/controllers/ads/upload-ad.js` para importarse en `controller/ads/index.js` y que desde allí se exporte al resto del sistema o se implemente en una función que sea la que realmente se exporta al resto del sistema

2022-12-06 21:39 UTC, Hector1567XD commented
@HopeAero mrc dale clic a "Resolve conversation" para uno saber cuales comentarios ya estan hechos y cuales no xD

2022-12-07 22:14 UTC, Noralgorithm approved these changes
LGTM

2022-12-09 02:22 UTC, HopeAero commented on controller/uploadAd.js
> +
si eres esquisito vale

2022-12-09 11:53 UTC, Hector1567XD commented
@HopeAero no me referia solamente a cambiar "controller" por "controllers" xD

2022-12-09 11:54 UTC, Hector1567XD approved these changes

2022-12-10 16:56 UTC, merged