Main teams
Edusus/project-ids-backend pull request #8
Opened 2022-12-04 18:02 UTC by DaikoneKisu

Cree esta rama intermedia porque la de teams no estaba relacionada al main xd. Resolví los conflictos.

2022-12-06 18:57 UTC, HopeAero approved these changes

2022-12-07 22:14 UTC, Noralgorithm approved these changes
LGTM

2022-12-09 11:58 UTC, Hector1567XD requested changes

2022-12-09 11:58 UTC, Hector1567XD commented on controllers/teams/poster.js
> +    }
Este approach esta dudosisimo xD, pero................. independientemente de.... haz que esto sea un helper por que se va a usar en demaciados sitios

```suggestion
    filepath = getImagePath(req.file.filename);
```

En `/src/helpers/get-image-path.js`:

```
function getImagePath(image) {
   const img_relative_dir = '/' + imgController.img_relative_dir.replaceAll('\\', '/') + '/';

    if (process.env.USINGIMGHOST == 'true') {
      return `${process.env.IMGURL}${img_relative_dir}${image}`;
    }
    
    return`${process.env.OFFSIDEURL}${img_relative_dir}${image}`;
}

```

2022-12-11 01:20 UTC, DaikoneKisu commented on controllers/teams/poster.js
> +    }
Ok papi

2022-12-21 16:23 UTC, Hector1567XD approved these changes
Luego con mas tiempo vemos la otra correcion

2022-12-21 16:23 UTC, Hector1567XD commented on controllers/teams/poster.js
> +    }
Luego con mas tiempo vemos la otra correcion

2022-12-21 17:54 UTC, merged